name: BowWarfare
version: 1.0B1
description: BowGame with infinite arrows.
Author: Aubli

main: me.Aubli.BowWarfare.BowWarfare

commands:
    bw:
        usage: /<command> help
        description: BW comands